import {
  BarChart3,
  Calendar,
  Clapperboard,
  FileText,
  Globe,
  HardDrive,
  Image as ImageIcon,
  KeyRound,
  Languages,
  LayoutGrid,
  Mail,
  Map,
  MessageSquare,
  Monitor,
  Network,
  Search,
  Shield,
  StickyNote,
  type LucideIcon,
} from "lucide-react";
import type { ServiceCategory } from "@/lib/schemas";

export const categoryIcons: Record<ServiceCategory, LucideIcon> = {
  search: Search,
  email: Mail,
  storage: HardDrive,
  photos: ImageIcon,
  browser: Globe,
  maps: Map,
  calendar: Calendar,
  docs: FileText,
  video: Clapperboard,
  appstore: LayoutGrid,
  authenticator: KeyRound,
  notes: StickyNote,
  translate: Languages,
  dns: Network,
  analytics: BarChart3,
  messaging: MessageSquare,
  os: Monitor,
  vpn: Shield,
};
